# Use the minimal version according to used features and syntax
version: "2"

networks:
  test-task:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.220.0/28

volumes:
  test-task-mysql-volume:
  test-task-mysql-test-volume:

services:
  http:
    image: nginx:stable-alpine
    container_name: test-task-nginx
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./application/public:/var/www/html/public:delegated
    depends_on:
      - app
    networks:
      - test-task

  mysql:
    container_name: test-task-mysql
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "test-task-mysql-volume:/var/lib/mysql"
    networks:
      - test-task

  mysql-test:
    container_name: test-task-mysql-test
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_TESTING}"
      MYSQL_DATABASE: "${DB_DATABASE_TESTING}"
      MYSQL_USER: "${DB_USERNAME_TESTING}"
      MYSQL_PASSWORD: "${DB_PASSWORD_TESTING}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "test-task-mysql-test-volume:/var/lib/mysql"
    networks:
      - test-task

#  phpmyadmin:
#    container_name: test-task-phpmyadmin
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      - PMA_ARBITRARY=1
#      - UPLOAD_LIMIT=20M
#    networks:
#      - test-task

  redis:
    image: "redis:5.0.3-alpine"
    container_name: test-task-redis
    restart: unless-stopped
    networks:
      - test-task
  # should be set in docker-compose.override.yml
  #    ports:
  #      - "${REDIS_PORT}:6379"

#  mailhog:
#    image: "mailhog/mailhog:v1.0.1"
#    container_name: test-task-mailhog
#    restart: unless-stopped
#    ports:
#      - "8080:8025"
  # should be set in docker-compose.override.yml
  #    ports:
  #      - "${MAILHOG_SMTP_PORT}:1025"
  #      - "${MAILHOG_WEB_PORT}:8025"

  npm:
    container_name: test-task-npm
    image: node:14
    command: npm start
    working_dir: /app
    entrypoint: [ "npm" ]
    volumes:
      - "./application/:/app"
    networks:
      - test-task

  app:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    container_name: test-task-app
    networks:
      - test-task
#    ports:
#      - "25:8025"
#          - "9003:9003"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9003 remote_enable=1 remote_autostart=1 xdebug.idekey=PHPSTORM
      PHP_IDE_CONFIG: "serverName=TestTaskDocker"
    volumes:
      - ./application:/var/www/html:delegated
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis
